# Generated by Django 5.1.4 on 2025-01-08 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
