# Generated by Django 5.1.4 on 2025-01-09 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_alter_members_phone'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='members',
            table='member_detail',
        ),
    ]
